# Template of a workflow to create, upate, delete and compile source documents on IRIS
name: Deploy to IRIS
# Trigger execute action
on:
  push:
    # All push to these branchs trigger the action Deploy to IRIS 
    branches:
      - <put you branch>
   # All puspull_requesth to these branchs trigger the action Deploy to IRIS
  pull_request:
    branches:
      - <put you branch>
#  Allow manually worflow execution
#  workflow_dispatch:

jobs:
  deploy-to-iris:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Get changed files and write the outputs to a JSON file
        id: modified-files
        uses: tj-actions/changed-files@v44
        with:
          separator: ","
          files: |
              **/*.{cls,mac,int,inc}
      - name: Depoly to IRIS
        uses: cristianojs02/iris-deployer@main
        with:
          host: '<IP or Host Name>'
          port: '<Port Number>'
          namespace_iris: '<CODENAMESPACE>'
          # 0 - HTTP, 1 - HTTPS 
          https: '0'
          base_api_url: '/api/atelier'
          version_api: 'v2'
          # Change if you don't want default flags compilation
          compilation_flags: 'cukb'
          # Used to extract from document name before sen to IRIS, avoiding Document Not found error.
          source_path: 'src/'
          # Use github secrets
          iris_usr: '<usr>'
          iris_pwd: '<pwd>'
          changed_files: '${{ steps.modified-files.outputs.all_changed_files }}'
          deleted_files: '${{ steps.modified-files.outputs.deleted_files }}'
